spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: app_user
    password: app_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: security   # ⭐ THÊM DÒNG NÀY
