spring.application.name=ThanhToanNoiBo
spring.datasource.url=jdbc:postgresql://[::1]:5432/app_db
spring.datasource.username=app_user
spring.datasource.password=app_password
debug=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbit
spring.rabbitmq.password=rabbit123