spring.application.name=ThanhToanNoiBo
spring.datasource.url=jdbc:postgresql://[::1]:5432/app_db?stringtype=unspecified
spring.datasource.username=app_user
spring.datasource.password=app_password
debug=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbit
spring.rabbitmq.password=rabbit123

vnpay.tmn-code=E2H3ZBMT
vnpay.hash-secret=9X2RZDXU0QC20CX3KKLDA7IEP0OX6IB6
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8080/api/payment/vnpay-return
vnpay.api-url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

jwt.secretKey=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
jwt.refreshExpiration=604800000