spring.application.name=ThanhToanNoiBo
spring.datasource.url=jdbc:postgresql://[::1]:5432/app_db?stringtype=unspecified
spring.datasource.username=app_user
spring.datasource.password=app_password
spring.jpa.hibernate.ddl-auto=update
debug=true

spring.data.redis.host=localhost
spring.data.redis.port=6380

spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0
spring.data.redis.lettuce.pool.max-wait=100ms

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbit
spring.rabbitmq.password=rabbit123

vnpay.tmn-code=E2H3ZBMT
vnpay.hash-secret=9X2RZDXU0QC20CX3KKLDA7IEP0OX6IB6
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:3000/payment/result
vnpay.api-url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

jwt.secretKey=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
jwt.refreshExpiration=604800000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyenquy12360@gmail.com
spring.mail.password=hvqj rcga chdk pges
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000
